import React from 'react';
import ReactDOM from 'react-dom';
import './base.css';
import './prettify.css';
import './sorter.js'

class HeaderElement extends React.Component {
  render() {
    return (
      <div>
        <span className ="strong"> {this.props.percentage}</span>
        <span className ="quiet"> {this.props.name}</span>
        <span className ="fraction"> {this.props.fraction}</span>
      </div>

      );
  }
}

class HeaderElements extends React.Component {
  render() {
    return(
      <div className='clearfix'>
        <div className='fl pad1y space-right2'>
          <HeaderElement percentage ='Unknown%' name='Statements' fraction='0/0'/>
        </div>
        <div className='fl pad1y space-right2'>
          <HeaderElement percentage ='Unknown%' name='Branches' fraction='0/0'/>
        </div>
        <div className='fl pad1y space-right2'>
          <HeaderElement percentage ='Unknown%' name='Functions' fraction='0/0'/>
        </div>
        <div className='fl pad1y space-right2'>
          <HeaderElement percentage ='Unknown%' name='Lines' fraction='0/0'/>
        </div>
      </div>
    );
  }
}
class HeaderBar extends React.Component {
  render() {
    return(
      <div>
      <div className='pad1'>
        <h1>All files</h1>
        <HeaderElements/>
      </div>
      <div className='status-line medium'></div>
    </div>
    );
  }
}



class Table extends React.Component {
  render() {
    return(
    <div>
      <div className='pad1'>
        <table className="coverage-summary">
          <thead>
            <tr>
              <th data-col="file" data-fmt="html" data-html="true" className="file">File</th>
              <th data-col="pic" data-type="number" data-fmt="html" data-html="true" className="pic"></th>
              <th data-col="statements" data-type="number" data-fmt="pct" className="pct">Statements</th>
              <th data-col="statements_raw" data-type="number" data-fmt="html" className="abs"></th>
              <th data-col="branches" data-type="number" data-fmt="pct" className="pct">Branches</th>
              <th data-col="branches_raw" data-type="number" data-fmt="html" className="abs"></th>
              <th data-col="functions" data-type="number" data-fmt="pct" className="pct">Functions</th>
              <th data-col="functions_raw" data-type="number" data-fmt="html" className="abs"></th>
              <th data-col="lines" data-type="number" data-fmt="pct" className="pct">Lines</th>
              <th data-col="lines_raw" data-type="number" data-fmt="html" className="abs"></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>

    </div>
    );
  }
}

class Wrapper extends React.Component {
  render() {
    return(
      <div className='content'>
        <HeaderBar />
        <Table />
        
      </div>
    );
  }
}
class Footer extends React.Component {
  render() {
    return (
      <div className='footer quiet pad2 space-top1 center small'>
        Code coverage
        generated by <a href="https://istanbul.js.org/" target="_blank" rel="noopener noreferrer">istanbul</a> at Thu Oct 19 2017 09:51:21 GMT+0000 (UTC)
      </div>
    );
  }
}
class Container extends React.Component {
  render() {
    return (
      <div className='container'>
        <Wrapper />
        <Footer />
      </div>
    );
  }
}


ReactDOM.render(
  <Container  />,
  document.getElementById('root')
);
